name: Deploy to gh-pages
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.2.0
      # Install Node.js and Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
      # Setup Cache
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v3.0.11
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # Yarn install (using cache if possible)
      - name: Install project dependencies
        run: yarn --prefer-offline
      # Generate dist files
      - name: Generate dist files
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: yarn generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          personal_token: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./dist
